name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v2

      # 2. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 필요 시 변경

      # 3. build 폴더를 S3로 동기화
      - name: Sync build folder to S3
        uses: aws-actions/s3-sync@v2
        with:
          source: './build'
          destination: 's3://testdasibar'  # 실제 버킷명 적용
          # 필요하다면 delete 옵션을 통해 S3에서 로컬에 없는 파일 삭제 가능
          # delete: true
